CREATE DATABASE CAR_RENTAL;

USE CAR_RENTAL;

CREATE TABLE IF NOT EXISTS CAR(
Vehicle_id INT(10) NOT NULL ,
License_no VARCHAR(20),
Model VARCHAR(20),
Year DATE,
Ctype VARCHAR(20),
Drate INT(10),
Wrate INT(10),
Status VARCHAR(20),
PRIMARY KEY (Vehicle_id),
UNIQUE (License_no)
);

CREATE TABLE IF NOT EXISTS CUSTOMER (
Cid INT(10) NOT NULL ,
Fname VARCHAR(1),
Lname VARCHAR(20),
Mobile INT(12),
Dno INT(10),
Vehicle_id INT(10),
FOREIGN KEY (Dno) REFERENCES DRIVER(Dno) ON UPDATE CASCADE,
FOREIGN KEY (Vehicle_id) REFERENCES CAR(Vehicle_id) ON UPDATE CASCADE,
PRIMARY KEY (Cid)
);

CREATE TABLE IF NOT EXISTS MEMBERS (
Mid INT(10) NOT NULL ,
Mtype VARCHAR(20),
Discount INT(10),
Duration VARCHAR(10),
Cid INT(10),
PRIMARY KEY (Mid),
FOREIGN KEY (Cid) REFERENCES CUSTOMER(Cid) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS  CUSTOMER_SERVICE(
Empid INT(10) NOT NULL ,
Name VARCHAR(20),
Mobile INT(12),
PRIMARY KEY (Empid)
);

CREATE TABLE IF NOT EXISTS  FEEDBACK(
Fid INT(10) NOT NULL ,
Message VARCHAR(140),
Email VARCHAR(50),
Empid INT(10),
Cid INT(10),
PRIMARY KEY (Fid),
FOREIGN KEY (Empid) REFERENCES CUSTOMER_SERVICE(Empid) ON UPDATE CASCADE,
FOREIGN KEY (Cid) REFERENCES CUSTOMER(Cid) ON UPDATE CASCADE,
);

CREATE TABLE IF NOT EXISTS  DRIVER(
Dno INT(10) NOT NULL,
PRIMARY KEY (Dno),
);

CREATE TABLE IF NOT EXISTS SELF (
Dlno INT(10) NOT NULL,
Name VARCHAR(20),
Insurance_no INT(12),
Dno INT(10),
PRIMARY KEY (Dlno),
FOREIGN KEY (Dno) REFERENCES DRIVER(Dno) ON UPDATE CASCADE,
);

CREATE TABLE IF NOT EXISTS CHAUFFEUR (
Chid INT(10) NOT NULL,
Name VARCHAR(20),
Gender Varchar(10),
Status VARCHAR(20),
Mobile INT(12),
Dno INT(10),
PRIMARY KEY (Chid),
FOREIGN KEY (Dno) REFERENCES DRIVER(Dno) ON UPDATE CASCADE,
);

CREATE TABLE IF NOT EXISTS RENTAL (
Rid INT(10) NOT NULL ,
Rdate DATE,
Amount INT(10),
Dno INT(10),
Vehicle_id INT(10),
PRIMARY KEY (Rid),
FOREIGN KEY (Vehicle_id) REFERENCES CAR(Vehicle_id) ON UPDATE CASCADE,
FOREIGN KEY (Dno) REFERENCES DRIVER(Dno) ON UPDATE CASCADE,
);

CREATE TABLE IF NOT EXISTS DAILY (
Rid INT(10) NOT NULL,
Sdate DATE,
Amount INT(10),
Nodays INT(10),
Vehicle_id INT(10),
Dno INT(10),
PRIMARY KEY (Rid),
FOREIGN KEY (Rid) REFERENCES RENTAL(Rid) ON UPDATE CASCADE,
FOREIGN KEY (Vehicle_id) REFERENCES CAR(Vehicle_id) ON UPDATE CASCADE,
FOREIGN KEY (Dno) REFERENCES DRIVER(Dno) ON UPDATE CASCADE,
);

CREATE TABLE IF NOT EXISTS WEEKLY(
Rid INT(10) NOT NULL,
Sdate DATE,
Amount INT(10),
Noweeks INT(10),
Vehicle_id INT(10),
Dno INT(10),
PRIMARY KEY (Rid),
FOREIGN KEY (Rid) REFERENCES RENTAL(Rid) ON UPDATE CASCADE,
FOREIGN KEY (Vehicle_id) REFERENCES CAR(Vehicle_id) ON UPDATE CASCADE,
FOREIGN KEY (Dno) REFERENCES DRIVER(Dno) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS BILL (
Bno INT(10) NOT NULL,
BDate DATE,
Advance INT(10),
Discount INT(10),
Drivercharge INT(10),
Famount INT(10),
Rid INT(10),
Cid INT(10),
PRIMARY KEY (Bno),
FOREIGN KEY (Rid) REFERENCES RENTAL(Rid) ON UPDATE CASCADE,
FOREIGN KEY (Cid) REFERENCES CUSTOMER(Cid) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS OWNS (
Owner_id INT(10) NOT NULL,
Vehicle_id INT(10),
PRIMARY KEY (Owner_id),
FOREIGN KEY (Owner_id) REFERENCES OWNER(Owner_id) ON UPDATE CASCADE,
);

CREATE TABLE IF NOT EXISTS OWNER (
Owner_id INT(10) NOT NULL,
PRIMARY KEY (Owner_id)
);

CREATE TABLE IF NOT EXISTS INDIVIDUAL (
Ssn INT(10) NOT NULL,
Name VARCHAR(20),
Owner_id INT(10),
PRIMARY KEY (Ssn),
FOREIGN KEY (Owner_id) REFERENCES OWNER(Owner_id) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS BANK (
Bid INT(10) NOT NULL,
Bname VARCHAR(20),
City VARCHAR(20),
Owner_id INT(10),
PRIMARY KEY (Bid),
FOREIGN KEY (Owner_id) REFERENCES OWNER(Owner_id) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS COMPANY (
Compid INT(10) NOT NULL,
Cname VARCHAR(20),
Owner_id INT(10),
PRIMARY KEY (Compid),
FOREIGN KEY (Owner_id) REFERENCES OWNER(Owner_id) ON UPDATE CASCADE
);